---
# ------------------- Dosec Service ------------------- #

apiVersion: v1
kind: Service
metadata:
  name: dosec-db
  namespace: dosec
spec:
  type: NodePort
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30432
  selector:
    app: dosec-db

---
# ------------------- Dosec Deployment ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dosec-db
  namespace: dosec
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dosec-db
  template:
    metadata:
      labels:
        app: dosec-db
    spec:
      imagePullSecrets:
      - name: registry-key
      containers:
      # ------------------- db ------------------- #
      - name: dosec-db
        image: hub.dosec.cn/library/dosec-db:2021-04-01T18.33.54V2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
      serviceAccountName: dosec-sa
