---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mg
spec:
  type: NodePort
#  externalTrafficPolicy: Local
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 8446
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mg
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: registry-key
     # nodeSelector:
     #   node-role.kubernetes.io/master: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
        - name: mysql
          image: hub.dosec.cn/honeypot/mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
